"""
agents/writer.py
----------------
Produces the final natural-language answer. Called by the Orchestrator on
all three paths (sql / direct / clarify), with different inputs:

  sql path:     rows + user_question — invoked INSIDE the orchestrator's
                `_write_grounded_answer` hard-block loop. On retry attempts
                (up to MAX_GROUNDEDNESS_RETRIES = 2) the Writer also receives
                `previous_text` (the rejected prior output) and
                `groundedness_feedback` (the unmatched numbers + a reminder
                of the grounding constraint).
  direct path:  user_question + planner_plan; no groundedness loop applies.
  clarify path: usually not called — Planner's clarifying question is returned
                directly. But we still handle it here if the Orchestrator
                routes through us.

The Writer's system prompt (agents/prompts/writer.txt) forbids referencing
UI affordances (Excel button, Show SQL expander, agent-trace expander,
chart image) and forbids apologizing for charts that didn't render — the
Streamlit frontend surfaces those automatically.
"""

from __future__ import annotations

import json

from agents.llm import call_llm, load_prompt, MODEL_HAIKU


_SYSTEM_PROMPT: str | None = None

def _system_prompt() -> str:
    global _SYSTEM_PROMPT
    if _SYSTEM_PROMPT is None:
        _SYSTEM_PROMPT = load_prompt("writer")
    return _SYSTEM_PROMPT


def write_answer(
    user_question: str,
    *,
    rows: list[dict] | None = None,
    columns: list[str] | None = None,
    path: str = "sql",
    plan: str = "",
    caveat: str | None = None,
    previous_text: str | None = None,
    groundedness_feedback: str | None = None,
    safe_values: str | None = None,
) -> str:
    """
    Inputs
    ------
    user_question         : the original user question
    rows                  : SQL result rows (sql path)
    columns               : column names (sql path)
    path                  : 'sql' | 'direct' | 'clarify'
    plan                  : Planner's plan string (direct path uses this as
                            the intent; clarify path uses this as the literal
                            clarifying question)
    caveat                : (optional) prefix added by the Orchestrator /
                            Supervisor when shipping a partial answer
    previous_text         : (optional) the previous Writer output that was
                            rejected by the groundedness check
    groundedness_feedback : (optional) the unmatched-numbers feedback string;
                            paired with previous_text on retry attempts
    safe_values           : (optional) a pre-computed Markdown section listing
                            the safe derivations the groundedness check will
                            accept (grand totals, top-N partial sums, per-group
                            subtotals, per-group row counts). Generated by
                            `tools.groundedness.safe_derivations_summary` and
                            passed by the orchestrator. Takes arithmetic OFF
                            the Writer so it picks from this list instead of
                            computing values that might miss the candidate set.

    Returns
    -------
    Plain markdown answer.
    """

    if path == "clarify":
        # Just return the planner's clarifying question; no LLM call needed.
        return plan.strip() if plan else "Could you clarify what you'd like to know?"

    parts = [f"## User question\n{user_question.strip()}"]

    if path == "direct":
        parts.append(f"## Path\ndirect (conversational, no DB query)")
        parts.append(f"## Planner plan\n{plan}")
    else:  # sql
        parts.append(f"## Path\nsql")
        if columns:
            parts.append(f"## Columns\n{', '.join(columns)}")
        if rows is not None:
            # Cap the JSON payload to keep prompt size reasonable.
            preview = rows[:30]
            parts.append(
                "## Rows (JSON; up to 30 shown)\n"
                + json.dumps(preview, default=str, indent=2)
            )
            if len(rows) > 30:
                parts.append(f"_(truncated; total rows: {len(rows)})_")

    # Pre-computed safe derivations — injected on the SQL path whenever
    # the orchestrator provides them. The Writer should treat this as the
    # canonical list of citeable values to avoid computing its own group
    # sums (which is the main historical source of groundedness misses).
    if safe_values and path == "sql":
        parts.append(safe_values)

    if previous_text and groundedness_feedback:
        parts.append(
            "## Previous attempt — REJECTED by groundedness check\n"
            f"Previous text:\n{previous_text}\n\n"
            f"Reviewer feedback:\n{groundedness_feedback}\n\n"
            "Write a NEW answer that satisfies the groundedness constraint. "
            "Pick numbers ONLY from the 'Safe values for grounding' section "
            "above (or individual row cells). Do not repeat the previous "
            "attempt. If you cannot make a useful answer under this "
            "constraint, say so concisely in 1-2 sentences."
        )

    if caveat:
        parts.append(f"## Caveat to include up front\n{caveat}")

    parts.append("Write the final answer for the user, following the rules.")

    user_block = "\n\n".join(parts)

    return call_llm(
        system=_system_prompt(),
        user=user_block,
        model=MODEL_HAIKU,
        # Temp 0 for determinism — same question on same data should
        # produce the same answer. This eliminates the failure mode where
        # the first attempt happened to compose unsafe numbers and the
        # second attempt happened to compose safe ones.
        temperature=0.0,
        max_tokens=800,
    )
